[Feature] Add customization of the `:BindAddress` web server option
Shopify/shopify-cli pull request #1609
Opened 2021-10-05 19:41 UTC by tyler-eon

### WHY are these changes introduced?

You cannot reliably run `shopify theme serve` within a container that uses port-forwarding because the `:BindAddress` option for `WEBrick` is incorrect. At present, there's no option to modify this option.

### WHAT is this pull request doing?

Adds a `--bind=HOST` option to `shopify theme serve` so that developers can choose what local host address to bind the web server to. In most cases, binding to `0.0.0.0` in a container will ensure that port-forwarding can work properly on the developer's host machine, but there could also be other cases where some other host address is applicable.

### Update checklist

- [x] I've added a CHANGELOG entry for this PR (if the change is public-facing)
- [x] I've considered possible cross-platform impacts (Mac, Linux, Windows).
- [x] I've left the version number as is (we'll handle incrementing this when releasing).

2021-10-05 19:51 UTC, tyler-eon commented
Forgot to add a test originally, just added it. Tested locally as well running in a container based on `ruby:3.0.2-alpine` and I can successfully test themes on my computer by using port-forwarding and navigating to `127.0.0.1:9292` in my browser when executing `shopify theme serve --bind 0.0.0.0`.

2021-10-06 16:37 UTC, tyler-eon commented on lib/shopify_cli/theme/dev_server.rb
> +        def start(ctx, root, bind: "127.0.0.1", port: 9292)
That's a good question. I only know that I found a solution using `0.0.0.0` on my virtualized environment but I was using software that didn't handle names, only IP numbers, let me double-check if that works in a virtualized environment and I'll get back to you.

2021-10-08 09:27 UTC, pepibumur commented
Thanks a lot, @tyler-eon for your thorough explanation.
The stance that we take when it comes to flags is trying to infer and provide defaults as much as possible unless there's a strong case for making it configurable. Because arguments represent the public interface of the CLI, adding more flags presents developers with more options and more decisions they need to make. 

Because the mapping between `localhost` and 127.0.0.1 lives in the [/etc/hosts](https://www.ibm.com/docs/en/aix/7.2?topic=formats-hosts-file-format-tcpip#:~:text=Description,name%20into%20its%20Internet%20address).) file, what do you think about the following logic: *if localhost is defined, we point to localhost, otherwise we default to 127.0.0.1.* Am I right assuming that addresses your needs and most users'?

> For context, I've got another PR I'm working on to allow people using mounted folders to enable force_polling in the listen gem. FS event notifications aren't reliable in container environments depending on how files are being modified. If you mount a host folder into the container and make changes on the host, depending on the environment configuration you might not ever get an FS event and therefore won't trigger the hot reload. Enabling force_polling is the only guaranteed workaround in the listen gem and would allow hot reloading to work, although with potentially a slight delay between file modifications and reloading. Still better than restarting the dev server every time you make an edit though.

This is something we addressed as part of [this](https://github.com/Shopify/shopify-cli/pull/1542), note there that we are exploring the idea of detecting when listening file changes don't work and defaulting to polling in those cases. This is in line with what I shared above. Can we accurately detect X and default to the right configuration for that? If so, we do it, otherwise, we provide an argument.

> But now we're getting into the realm of how many command-line options is too many? Do we just keep adding these things as options or is it preferable to look at environment variables that can be baked into the container spec? Curious to know your thoughts.

If we agree we need to make something configurable, and the scope is a single command, then an **argument** is the most suitable place. If we want to make that configurable at the project or environment level, then we'll also allow setting a value there that can be overridden through arguments. In very few cases we use environment variables. It's mostly for configurations that are rarely used. For example, if the CLI errors, it tells you to run it again with an environment variable to see the whole stacktrace. Because you are not doing that all the time, it doesn't make sense to include it as an argument that you see every time you print the help.

Please, confirm if the `/etc/hosts` idea addresses your need. In that case, I recommend taking that files as a source of truth and do some pattern matching to extract the information that you need.

2021-10-15 14:52 UTC, pepibumur commented
> If localhost is defined by default and set to 127.0.0.1 then we'll run into the same problem. Unless you're suggesting that users edit /etc/hosts and redefine the localhost mapping, which is significantly less developer-friendly than just adding a command-line option.

100% agree with you. Developer-friendliness is something we optimize for, and therefore any inconvenience the CLI presents has to be mitigated.

> Unless I'm missing some feature that would simplify that process?

You are completely right. Thanks for your thorough explanation.

I'm looping @MeredithCastile who will help us with the name of the argument and the help.

2021-10-15 14:54 UTC, pepibumur requested changes
Thanks a lot for contributing to this one @tyler-eon. Contributions are always appreciated.
Once we have the help updated and the :+1: from @MeredithCastile we'll be in the position to merge it if CI is happy about your changes too.

2021-10-20 22:09 UTC, tyler-eon commented
@pepibumur Sounds good, appreciate it 👍

2021-10-20 22:27 UTC, MeredithCastile commented
Just want to reiterate, @tyler-eon, how smart and helpful the context you've provided has been. Thank you.

@pepibumur, thanks for keeping the momentum going. Will follow up about the messaging.

2021-10-21 10:14 UTC, merged